# Generated by Django 2.2.5 on 2020-02-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200209_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='active_on',
            field=models.DateTimeField(null=True),
        ),
    ]
