# Generated by Django 2.2.5 on 2020-02-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_author_active_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=4000),
        ),
    ]
